install.packages(c('UpSetR','optparse','argparse','Rtsne','ggplot2','pheatmap','RColorBrewer', 'cowplot', 'reshape2','Hmisc','igraph','ggrepel','plyr','rsvd', 'dplyr', 'purrr', 'uwot', 'egg','Seurat'), repos="http://cran.us.r-project.org", "viridis")
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("impute", version = "3.8")
BiocManager::install("preprocessCore", version = "3.8")
BiocManager::install("GO.db", version = "3.8")
BiocManager::install("XVector", version = "3.8")
BiocManager::install("IRanges", version = "3.8")
BiocManager::install("biomaRt", version = "3.8")
BiocManager::install("rDGIdb", version = "3.8")
BiocManager::install("limma", version = "3.8")
BiocManager::install("rhdf5", version = "3.8")
BiocManager::install("edgeR", version = "3.8")
BiocManager::install("scater", version = "3.8")
BiocManager::install("scran", version = "3.8")
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene", version = "3.8")
BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene", version = "3.8")
BiocManager::install("org.Hs.eg.db", version = "3.8")
BiocManager::install("GSVA", version = "3.8")
BiocManager::install("aroma.light", version = "3.8")
BiocManager::install("MAST", version = "3.8")
BiocManager::install("GGally", version = "3.8")
BiocManager::install("WGCNA", version = "3.8")
BiocManager::install("DropletUtils")
if(!require(devtools)){
  install.packages("devtools") # If not already installed
}
devtools::install_github("JinmiaoChenLab/Rphenograph")
devtools::install_github(repo = 'ChristophH/sctransform')
